export type ConferenceType = "jugru" | "onteko";
export const JUGRU_CONFERENCE_NAME = [
  "holyjs.ru",
  "heisenbug.ru",
  "biasconf.ru",
  "cppconf.ru",
  "cargo-cult.club",
  "devoops.ru",
  "dotnext.ru",
  "flowconf.ru",
  "gofunc.ru",
  "hydraconf.com",
  "imlconf.com",
  "inbetween.ru",
  "jpoint.ru",
  "jokerconf.com",
  "mobiusconf.com",
  "piterpy.com",
  "safecodeconf.ru",
  "smartdataconf.ru",
  "techtrain.ru",
  "vtconf.com",
  "sysconf.pro",
] as const;
export const ONTEKO_CONFERENCE_NAME = [
  "frontendconf.ru",
  "techfounders.ru",
  "datainternals.ru",
  "devrelconf.ru",
  "industrialconf.ru",
  "appsconf.ru",
  "aiconf.ru",
  "highload.ru",
  "bundle.highload.ru",
  "teamleadconf.ru",
  "devopsconf.io",
  "ontico.ru",
  "1cconf.ru",
  "phprussia.ru",
] as const;

export const CONFERENCE_NAME = [
  ...JUGRU_CONFERENCE_NAME,
  ...ONTEKO_CONFERENCE_NAME,
] as const;
